//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

[System.Serializable]


public class MyScriptableObjectClass : ScriptableObject
{
	public string objectName;
	public bool colorIsRandom = false;
	public Color thisColor = Color.white;
	public Vector3[] spawnPoints;
}


